services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: shortener
    ports: ["5432:5432"]
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7
    ports: ["6379:6379"]

  app1:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://app:app@postgres:5432/shortener
      REDIS_URL: redis://redis:6379
      BASE_URL: http://localhost:8080
      DISABLE_CACHE: ${DISABLE_CACHE:-0}
    depends_on: [postgres, redis]

  app2:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://app:app@postgres:5432/shortener
      REDIS_URL: redis://redis:6379
      BASE_URL: http://localhost:8080
      DISABLE_CACHE: ${DISABLE_CACHE:-0}
    depends_on: [postgres, redis]

  nginx:
    image: nginx:alpine
    ports: ["8080:80"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [app1, app2]